---
name: TP_Information_System
services:
  db:
    image: postgres:17.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tp_info
    volumes:
      - ./db.d/:/docker-entrypoint-initdb.d/
  moteur_jeu:
    build:
      context: ./moteur_jeu
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "9990"
    develop:
      watch:
        - action: rebuild
          path: ./moteur_jeu
  server_http:
    build:
      context: ./serveur_http
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - moteur_jeu
    environment:
      TP_GAME_SERVER_ADDRESS: moteur_jeu
    ports:
      - "9999:9999"
    develop:
      watch:
        - action: rebuild
          path: ./serveur_http
  server_tcp:
    build:
      context: ./serveur_tcp
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - moteur_jeu
    environment:
      TP_GAME_SERVER_ADDRESS: moteur_jeu
    ports:
      - "9998:9999"
    develop:
      watch:
        - action: rebuild
          path: ./serveur_tcp
